PROJECT_NAME := default

generate:
	mvn archetype:generate -DgroupId=com.${PROJECT_NAME} -DartifactId=${PROJECT_NAME} -DarchetypeArtifactId=maven-archetype-quickstart -DinteractiveMode=false
	cd ${PROJECT_NAME}